<empty>

diff --git a/util/scidem b/util/scidem
--- a/util/scidem
+++ b/util/scidem
@@ -6,11 +6,11 @@ SCI=$1
 export SCI
 if [ -f $3  ]; then rm $3;fi;
 trap "rm -f /tmp/$2.$$ /tmp/$2.$$.res /tmp/$2.$$.err /tmp/$2.$$.diff\
-	;exit 1"  1 2 13 15
+        ;exit 1"  1 2 13 15
 echo "clear;lines(0);deff('[]=bugmes()','write(%io(2),''error on test'')');\
-	diary('$3');driver('Pos');" >> /tmp/$2.$$ ;
+        diary('$3');driver('Pos');" >> /tmp/$2.$$ ;
 sed     -e "s/pause,end/bugmes();quit;end/" \
-	-e "s/halt()//" \
+        -e "s/halt()//" \
         $2 >> /tmp/$2.$$ ;
 echo "diary(0);xend();quit;quit;quit;quit;quit;quit;" >> /tmp/$2.$$ ;
 ($SCI/bin/scilex -nw < /tmp/$2.$$ > /tmp/$2.$$.res ) 2> /tmp/$2.$$.err ;
@@ -18,14 +18,14 @@ sed -e "s/ \./0\./g" -e "s/E+/D+/g" -e "s/E-/D-/g" -e "s/-\./-0\./g" -e "s/^-->/
 grep -v "xinit(" $3.n | grep -v "diary(" | grep -v "exec("  > $3
 rm -f $3.n
 if ( grep error /tmp/$2.$$.res >  /dev/null ) ; then 
-	if [ $# != 4 ]; then 
-		echo "Test failed ERROR DETECTED  while executing $2" ;
-	fi;
+        if [ $# != 4 ]; then 
+                echo "Test failed ERROR DETECTED  while executing $2" ;
+        fi;
 else if [ -f $3.ref ];then 
-	if ( diff -w $3 $3.ref > /tmp/$2.$$.diff ) ;
-	then  echo Test passed ;
-	else  echo Test Failed SEE : diff -w  $3 $3.ref ;
-	fi;
+        if ( diff -w $3 $3.ref > /tmp/$2.$$.diff ) ;
+        then  echo Test passed ;
+        else  echo Test Failed SEE : diff -w  $3 $3.ref ;
+        fi;
       fi;
 fi;
 echo ---------------------------------------------------------- 
